### PR TITLE
Add bundler support

### PR DESCRIPTION
**Pull request by stardiviner**

### CODE REVIEW

**Comment by aaronbieber** [comment]
Jekyll commands also get prefixed with "bundle exec," note that `octopress--run-jekyll-command` calls `octopress--run-command`, which prefixes all commands with `(octopress--bundler-command-prefix)`.

You can test this by pressing `b b` to run a build and `!` to open the command output buffer and note that the command should be printed as "bundle exec jekyll build".

If this is not working for you please open a new issue with more details.

**Comment by stardiviner** [comment]
I tested, it does not prefix with `bundle exec` because it caused error.

```
Running `jekyll serve --drafts --unpublished'...

WARN: Unresolved specs during Gem::Specification.reset:
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
      rb-fsevent (>= 0.9.3)
      ffi (>= 0.5.0)
      celluloid-essentials (>= 0)
      celluloid-supervision (>= 0)
      celluloid-pool (>= 0)
      celluloid-fsm (>= 0)
      celluloid-extras (>= 0)
      hitimes (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/home/stardiviner/.gem/ruby/2.2.0/gems/jekyll-2.5.3/bin/jekyll:21:in `block in <top (required)>': cannot load such file -- jekyll/version (LoadError)
    from /home/stardiviner/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:18:in `program'
    from /home/stardiviner/.gem/ruby/2.2.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
    from /home/stardiviner/.rbenv/versions/2.2.0/bin/jekyll:23:in `load'
    from /home/stardiviner/.rbenv/versions/2.2.0/bin/jekyll:23:in `<main>'
```

and I checked your commit.
You add prefix into `octopress--run-octopress-command`, instead of `octopress--run-command`.
You can review it. https://github.com/aaronbieber/octopress.el/commit/fdfaf548321a5d8fd09d6c35118b64f36b892e3f

the problem is not on jekyll build, problem is on jekyll serve.

**Comment by aaronbieber** [comment]
I think you're misreading that diff, there are collapsed lines in between,
please view the full file:
https://github.com/aaronbieber/octopress.el/blob/master/octopress.el#L793

You may need to pull the latest Octopress source manually; MELPA probably
hasn't rebuilt the latest yet, with my current changes.

**Comment by stardiviner** [comment]
Hmm, that explained. I checked, MELPA updated. Have you tested the server command? it really can't work. I checked the source code after update MELPA, and restart Emacs, the updated package has your diff code.

**Comment by stardiviner** [comment]
After a few days, I updated MELPA many times, use command `[s]` server command in `octopress-status`. It still cause same error. I tested all other commands, all other jekyll commands are prefixed with `bundle exec` except the `jekyll serve`.

**Comment by aaronbieber** [comment]
I found the issue and pushed a fix in 2e068887b. It may still take MELPA a while to pick it up.

**Pull request closed without merging**
